# sudo docker run -dp 127.0.0.1:8080:8080 \
# -w /app --mount type=bind,src="$(pwd),target=/app" \
# node:lts-alpine \
# sh -c "npm ci && npx prisma generate && npm run start:dev"

services:
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./backend:/app # Bind mount pour hot reload (src: "$(pwd)", target: /app)
      - /app/node_modules
    working_dir: /app  # -w /app
    command: sh -c "npm ci && npx prisma generate && npm run start:dev"
    stdin_open: true   # garde le conteneur interactif en dev
    environment: 
      - NODE_ENV=development
    
  # db:
  #   image: mysql:9.3

  