# -----------------------------------------------------------
# Dockerfile.dev
# -----------------------------------------------------------

FROM node:22.19.0
WORKDIR /app


# Depandence
COPY package.json ./
COPY package-lock.json ./
COPY prisma ./prisma
RUN npm install
RUN npx prisma generate

COPY . .

EXPOSE 5000

ENV NODE_ENV=developement

CMD ["npm","run","start:dev"]

