# sudo docker run -dp 127.0.0.1:8080:8080 \
# -w /app --mount type=bind,src="$(pwd),target=/app" \
# node:lts-alpine \
# sh -c "npm ci && npx prisma generate && npm run start:dev"


services:
  mysql:
    image: mysql:8.0
    container_name: mysql_drop_shop
    hostname: mysqlhost
    ports:
      - '127.0.0.1:4000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root            
      MYSQL_DATABASE: drop_shop            
      MYSQL_USER: tsitohaina             
      MYSQL_PASSWORD: azerty#        
    volumes: 
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
     - app-network
    healthcheck:                        
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 60s
      interval: 20s
      timeout: 5s
      retries: 5
  backend: 
    build: 
      context: .
      dockerfile: docker/source.dockerfile
    container_name: backend_drop_shop
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./source:/app
      - /app/node_modules
    stdin_open: true   
    tty: true
    environment: 
      - NODE_ENV=development
      - DATABASE_URL=mysql://tsitohaina:azerty%23@mysqlhost:3306/drop_shop
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network    
  prisma_studio:
    build:
      context: .
      dockerfile: docker/prisma-sutdio.dockerfile
    container_name: prisma_studio
    ports:
      - '127.0.0.1:5555:5555'
    stdin_open: true   
    tty: true
    environment: 
      - DATABASE_URL=mysql://tsitohaina:azerty%23@mysqlhost:3306/drop_shop
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network   
volumes:
  mysql-data:
networks:
  app-network:


  
  