openapi: 3.0.0
info:
  title: API Documentation
  description: API documentation for user authentication
  version: 1.0.0

paths:
  /:
    get:
      description: Welcome to swagger-jsdoc!
      responses:
        '200':
          description: Returns html.
  
  /signup:
    post:
      summary: Signup a new user
      description: Create a new account for the user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signup'
      responses:
        '200':
          description: Successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: id
                    type: number
                    example: 9
                  token:
                    description: token
                    type: string
                    example: "fzeOpdzafeb vz fdh befh hjfb vizrbviudzviuzivnzdvbz"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "user already exist, change email or tel"
                    exemple: "all propriety required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "internal server error"

components:
  schemas:
    Signup:
      type: object
      required:
        - firstname
        - lastname
        - email
        - password
        - tel
        - pays
        - adress
        - role
      properties:
        firstname:
          type: string
          example: "John"
        lastname:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
        password:
          type: string
          format: password
          example: "securepassword123"
        tel:
          type: string
          example: "+261 34 12 345 67"
        pays:
          type: string
          example: "Madagascar"
        adress:
          type: string
          example: "123 Main Street, Antananarivo"
        role:
          type: string
          enum: [SELLER, BUYER, ADMIN]
          example: "BUYER"
        code postal:
          type: string

tags:
  - name: Auth
    description: Authentication routes
